# Generated by Django 5.2.7 on 2025-10-20 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_dish', models.CharField(max_length=60, verbose_name='Название блюда')),
                ('description', models.TextField(verbose_name='Описание')),
                ('history', models.TextField(verbose_name='История блюда')),
                ('ingredients', models.TextField(verbose_name='Ингредиенты')),
                ('cooking_time', models.PositiveIntegerField(verbose_name='Время приготовления (в минутах)')),
                ('calories', models.PositiveIntegerField(verbose_name='Калорийность (ккал)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('photo', models.ImageField(upload_to='images/')),
                ('trailer', models.TextField()),
                ('views', models.IntegerField(default=0)),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_journey.category')),
            ],
        ),
    ]
