# Generated by Django 5.2.7 on 2025-10-23 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_journey', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Название кухни'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='cuisine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_journey.category', verbose_name='Название кухни'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='photo',
            field=models.ImageField(upload_to='images/', verbose_name='Фотографие блюда'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='trailer',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на ютуб видео приготовление'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
