# Generated by Django 5.2.7 on 2025-11-06 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_journey', '0003_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Фото профиля')),
                ('is_online', models.BooleanField(default=False, verbose_name='Статус профиля')),
                ('about', models.CharField(blank=True, max_length=250, null=True, verbose_name='О себе')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='Место нахождения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль ',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
